// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glidufqwkkzhliwuqmvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsaWR1ZnF3a2t6aGxpd3VxbXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNjA0NjYsImV4cCI6MjA1MzYzNjQ2Nn0.ChofcF4suDKXmkgdsWu54ggmQPLqbHWS3cCZ1qVMixY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);